###
GET http://localhost:8080/api/foodticket

###
GET http://localhost:8080/api/foodticket/getAllValidTickets


###
GET http://localhost:8080/foodticket/overview?
    last12Months=false

###
GET http://localhost:8080/foodticket/admin-overview-info-box?
    last12Months=false


###
GET http://localhost:8080/foodticket/findByEmployee/1

###
GET http://localhost:8080/foodticket/listAdminTickets?employeeName=nna


###
GET http://localhost:8080/foodticket/table-clearing


###
GET http://localhost:8080/foodticket/table-clearing/4