###
GET http://localhost:8080/foodticket

###
GET http://localhost:8080/foodticket/listAdminTickets
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6Im1heC5tdXN0ZXJtYW5uQGZpcm1hLmF0IiwiaWQiOjEsImdyb3VwcyI6WyJBRE1JTiJdLCJpYXQiOjE3ODQzMDkyMDAsImV4cCI6MTc4NDM0NTIwMCwianRpIjoiZGE0OGNlOWQtMzA0My00MjQwLTgwOWItN2E1OGQ4NjM2ZmU5In0.Z3-D0vjIuMOZT3_PGd8XWwOB5RmbCtvllPe8bjx-3TAOlfGM0bWd2_2uluOFNx2Mh_OOeaiK_WL90_NZHQw_gC67lGUPVqfW2eEQPfTAULxFx48iugh19wJq1aEkMphEf60KebB9PIiuG-c5CP8XG8SFdLR3JJB0gfwi3-nbcRGfSDHlscD_q5_LKvlll8joV1bRPuQyIXfKnhiQvXuiKWfnPSxSNhgheVmsV-IhQ__rk_ELe2sX7Q7tE0pbaxvHDvjri4yJbzcsnkBeEQkRIPmdtIPjGL_EV7JGhBP8n_8zEFsjfKC4BAwJS17gjfhw0SbJIGplA2TBS5z6VZRPsA

###
GET http://localhost:8080/api/foodticket/getAllValidTickets


###
GET http://localhost:8080/foodticket/overview?
    last12Months=false

###
GET http://localhost:8080/foodticket/admin-overview-info-box?
    last12Months=false


###
GET http://localhost:8080/foodticket/findByEmployee/1

###
GET http://localhost:8080/foodticket/2

###
GET http://localhost:8080/foodticket/listAdminTickets?employeeName=nna


###
GET http://localhost:8080/foodticket/table-clearing


###
GET http://localhost:8080/foodticket/table-clearing/4

###
GET http://localhost:8080/foodticket/clearing-info-box

###
DELETE http://localhost:8080/foodticket/1

###
GET http://localhost:8080/foodticket/conflicts

###
GET http://localhost:8080/foodticket/conflicts?status=CONFLICT

###
PUT http://localhost:8080/foodticket/changeStatus/1/CONFLICT


###
PUT http://localhost:8080/foodticket/adminEditTicket/1
Content-Type: application/json

{
  "employeeName": "Max Mustermann",
  "useDate": "2026-07-18",
  "tier": "EMPLOYEE",
  "costOrder": "IT",
  "restaurantName": "Pizzeria Bella Italia",
  "adminName": "Anna Admin",
  "status": "CHECKED",
  "description": "Kostenstelle und Restaurant korrigiert. Ticket erfolgreich abgeglichen."
}