###
POST http://localhost:8080/restaurantUser/register
Content-Type: application/json

{
  "firstName": "Max",
  "lastName": "Mustermann",
  "email": "max.mustermann@porsche.at",
  "passwordHash": "password123",
  "role": "ADMIN"
}

###
POST http://localhost:8080/restaurantUser/login
Content-Type: application/json

{
  "email": "stefan.leitner@firma.at",
  "password": "password123"
}


###
GET http://localhost:8080/restaurantUser/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6InN0ZWZhbi5sZWl0bmVyQGZpcm1hLmF0IiwiaWQiOjEsInRlbmFudElkIjoxLCJncm91cHMiOlsiUkVTVEFVUkFOVF9BRE1JTiJdLCJpYXQiOjE3ODgxMTU3MDUsImV4cCI6MTc4ODE1MTcwNSwianRpIjoiMTdiMjQyMTctNWU0OC00NWFjLWI3YjItNTE0MWUxNWM0YTE2In0.ra0G8FHUch8IL21bD6CW2H9CgBRQc6MWFIAamq-lo-igqsMo69XMorq3N3fOUPsXZeYeQvdF4uJTiTuZcZUONytffilUegM0DK-lMuIAj_1kKduSRaBLtpmhyrAeaIqx9rs9bb0TG1pCaA6LTt_Otu_nGbSyU0XRgeWOfVM6FSr1LtzCIrEP8RnSZ-fQOMVCtqvfHhhUEHF95smKvzGN--tikY0sjmLAAT8hLWGASItoJNMfbBbCJoziSs2QDru9dWCtxzBVxRUEEdSjDBlEXP4_JLjrZAfaXnrHfGykid3tk-IPFhzrOZGfp3ICHxU9lX2H8fVFkIV9nS80iGC3pw


###
GET http://localhost:8080/foodticket/restaurantUser/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6InN0ZWZhbi5sZWl0bmVyQGZpcm1hLmF0IiwiaWQiOjEsInRlbmFudElkIjoxLCJncm91cHMiOlsiUkVTVEFVUkFOVF9BRE1JTiJdLCJpYXQiOjE3ODgxMTU3MDUsImV4cCI6MTc4ODE1MTcwNSwianRpIjoiMTdiMjQyMTctNWU0OC00NWFjLWI3YjItNTE0MWUxNWM0YTE2In0.ra0G8FHUch8IL21bD6CW2H9CgBRQc6MWFIAamq-lo-igqsMo69XMorq3N3fOUPsXZeYeQvdF4uJTiTuZcZUONytffilUegM0DK-lMuIAj_1kKduSRaBLtpmhyrAeaIqx9rs9bb0TG1pCaA6LTt_Otu_nGbSyU0XRgeWOfVM6FSr1LtzCIrEP8RnSZ-fQOMVCtqvfHhhUEHF95smKvzGN--tikY0sjmLAAT8hLWGASItoJNMfbBbCJoziSs2QDru9dWCtxzBVxRUEEdSjDBlEXP4_JLjrZAfaXnrHfGykid3tk-IPFhzrOZGfp3ICHxU9lX2H8fVFkIV9nS80iGC3pw

