###
POST http://localhost:8080/restaurantUser/register
Content-Type: application/json

{
  "firstName": "Max",
  "lastName": "Mustermann",
  "email": "max.mustermann@porsche.at",
  "passwordHash": "password123",
  "role": "ADMIN"
}

###
POST http://localhost:8080/restaurantUser/login
Content-Type: application/json

{
  "email": "stefan.leitner@firma.at",
  "password": "password123"
}


###
GET http://localhost:8080/restaurantUser/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6InN0ZWZhbi5sZWl0bmVyQGZpcm1hLmF0IiwiaWQiOjEsInRlbmFudElkIjoxLCJncm91cHMiOlsiUkVTVEFVUkFOVF9BRE1JTiJdLCJpYXQiOjE3ODgyMDAzNDMsImV4cCI6MTc4ODU2MDM0MywianRpIjoiNTM0YWRlYWQtOTVhNC00NTQ3LTlkNmYtMTFhOGQ2M2IwNDBjIn0.pFpxAoQDQq3-svakYJZU3zq8U7qiz4e4EkI19eHOl8fI8GkL2H7gdZ2MTQUgCWcpvkLul_3wajMG30a0c_v-xrIYUuTY54Wj2mfAEw5LrFVrdn-fVcJvSXIB6GEeqbROio3ZW11v-0sTiK68XN1WF0v13lHA-dVAkLUJKlxygW_CRxesXFrFhRBFpmMrl5JpngIJ0-KxL6lPTlN0soOiF3cXO8BgDHmy89rm7b5ThL0kRcnb1go0-SK4OPls-jZYujSMdhvmR5_aFV9a8BWSQp3CYx1p5-2_-kc5yhWwkeS36Kv1I6ObzFvalIM497k4VrRmkoUmv9rDSyXDDjE_vw


###
GET http://localhost:8080/foodticket/restaurantUser/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6InN0ZWZhbi5sZWl0bmVyQGZpcm1hLmF0IiwiaWQiOjEsInRlbmFudElkIjoxLCJncm91cHMiOlsiUkVTVEFVUkFOVF9BRE1JTiJdLCJpYXQiOjE3ODgyMDAzNDMsImV4cCI6MTc4ODU2MDM0MywianRpIjoiNTM0YWRlYWQtOTVhNC00NTQ3LTlkNmYtMTFhOGQ2M2IwNDBjIn0.pFpxAoQDQq3-svakYJZU3zq8U7qiz4e4EkI19eHOl8fI8GkL2H7gdZ2MTQUgCWcpvkLul_3wajMG30a0c_v-xrIYUuTY54Wj2mfAEw5LrFVrdn-fVcJvSXIB6GEeqbROio3ZW11v-0sTiK68XN1WF0v13lHA-dVAkLUJKlxygW_CRxesXFrFhRBFpmMrl5JpngIJ0-KxL6lPTlN0soOiF3cXO8BgDHmy89rm7b5ThL0kRcnb1go0-SK4OPls-jZYujSMdhvmR5_aFV9a8BWSQp3CYx1p5-2_-kc5yhWwkeS36Kv1I6ObzFvalIM497k4VrRmkoUmv9rDSyXDDjE_vw
