###
GET http://localhost:8080/saas-admin/tenants

###
POST http://localhost:8080/saas-admin/tenant
Content-Type: application/json

{
  "name": "BMW2",
  "manager": "Max Mustermann",
  "email": "max.mustermann@bmw.at",
  "country": "Austria",
  "companySize": "Large"
}


###
GET http://localhost:8080/saas-admin/tenantByManager/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6Im1heC5tdXN0ZXJtYW5uQGZpcm1hLmF0IiwiaWQiOjEsInRlbmFudElkIjoxLCJncm91cHMiOlsiQURNSU4iXSwiaWF0IjoxNzg4MjAwMzY4LCJleHAiOjE3ODgzODAzNjgsImp0aSI6ImQ4NTcwZTg1LTNhNzMtNDJiNi1hODg2LTM1OTgyNmJiZGIxZiJ9.OWyQAQvTSrvKqJKN6sJWjaWOppUlt1H_2OHVWPfEgB7ka39HEPR4QOzdveROrNFvLkanIsMEueuw_iAzp1U0fHs1p_dVXSZTF07M6TC59zoO4sM3MBQhpQVaY5dKLmkAiLR2liIUaNBU9EhBWduru5xWYnqmIqWTdtCO8Lt8IjbuLdaBwsYtTuCebPN1X03FsBtTBOxoS3SyXTQ-Qw0IhPFZ5MChjIwqZlMzqcEkxJv2OlBxtklzLKTzA118UVUHswQc-80aPwGf60YX4zYMTlQojXXtabqbci8mwJ_uTLR-c0c6lu_P-AhjGe6QrHlh8UZwyCPGecColfmxgDD7OA

###
PUT http://localhost:8080/saas-admin/assign/2/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6Im1heC5tdXN0ZXJtYW5uQGZpcm1hLmF0IiwiaWQiOjEsInRlbmFudElkIjoxLCJncm91cHMiOlsiQURNSU4iXSwiaWF0IjoxNzg4MjAwMzY4LCJleHAiOjE3ODgzODAzNjgsImp0aSI6ImQ4NTcwZTg1LTNhNzMtNDJiNi1hODg2LTM1OTgyNmJiZGIxZiJ9.OWyQAQvTSrvKqJKN6sJWjaWOppUlt1H_2OHVWPfEgB7ka39HEPR4QOzdveROrNFvLkanIsMEueuw_iAzp1U0fHs1p_dVXSZTF07M6TC59zoO4sM3MBQhpQVaY5dKLmkAiLR2liIUaNBU9EhBWduru5xWYnqmIqWTdtCO8Lt8IjbuLdaBwsYtTuCebPN1X03FsBtTBOxoS3SyXTQ-Qw0IhPFZ5MChjIwqZlMzqcEkxJv2OlBxtklzLKTzA118UVUHswQc-80aPwGf60YX4zYMTlQojXXtabqbci8mwJ_uTLR-c0c6lu_P-AhjGe6QrHlh8UZwyCPGecColfmxgDD7OA
