###
GET http://localhost:8080/saas-admin/tenants

###
GET http://localhost:8080/saas-admin/tenant-overview
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6Im1heC5tdXN0ZXJtYW5uQGZpcm1hLmF0IiwiaWQiOjEsInRlbmFudElkIjoxLCJncm91cHMiOlsiU0FBU19BRE1JTiJdLCJpYXQiOjE3OTA1MzkwODMsImV4cCI6MTc5MDcxOTA4MywianRpIjoiNjNjYmJmMzUtZWM5MS00OGEyLWJkMjUtNmU4YjM4YmE3N2E0In0.r9pVx_rAfxo1Uc6qzRcZTyidUz2hTvDuJgkgRNHxl_pbnIPJcPde35eFEL41ZsICLRqdPt4JCaf8wguzGWs6iT8c2pkdG6FBLjxjax64JOiaiA-gouOJwuDC35jP1mLxB5EGISxjEjcj9-XYCaeS_ZeSQ8xDGBgUKhd2SMPc401rsLVkEyotfeyu4opo_jL4u9HdxAs87aaVak_QQvVi-cexklZ8Vt4fN2GGMAbFu1Fq13iy4NZWQpuMMj4_bip4R7JqYbnqFUo5aolK41luwgzI8pn0hIJvA9GMe3fRytL-cF3_5Z2_bTEXnc7avV08TDNw_Q2tw5vjcmA5hikdhQ",


###
POST http://localhost:8080/saas-admin/tenant
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6Im1heC5tdXN0ZXJtYW5uQGZpcm1hLmF0IiwiaWQiOjEsInRlbmFudElkIjoxLCJncm91cHMiOlsiU0FBU19BRE1JTiJdLCJpYXQiOjE3OTA1MzkwODMsImV4cCI6MTc5MDcxOTA4MywianRpIjoiNjNjYmJmMzUtZWM5MS00OGEyLWJkMjUtNmU4YjM4YmE3N2E0In0.r9pVx_rAfxo1Uc6qzRcZTyidUz2hTvDuJgkgRNHxl_pbnIPJcPde35eFEL41ZsICLRqdPt4JCaf8wguzGWs6iT8c2pkdG6FBLjxjax64JOiaiA-gouOJwuDC35jP1mLxB5EGISxjEjcj9-XYCaeS_ZeSQ8xDGBgUKhd2SMPc401rsLVkEyotfeyu4opo_jL4u9HdxAs87aaVak_QQvVi-cexklZ8Vt4fN2GGMAbFu1Fq13iy4NZWQpuMMj4_bip4R7JqYbnqFUo5aolK41luwgzI8pn0hIJvA9GMe3fRytL-cF3_5Z2_bTEXnc7avV08TDNw_Q2tw5vjcmA5hikdhQ",
Content-Type: application/json

{
  "name": "BMW2",
  "manager": "Max Mustermann",
  "email": "max.mustermann@bmw.at",
  "country": "Austria",
  "companySize": "Large",
  "primaryColor": "#005F99",
  "accentColor": "#FFFFFF"
}


###
GET http://localhost:8080/saas-admin/tenantByManager/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6Im1heC5tdXN0ZXJtYW5uQGZpcm1hLmF0IiwiaWQiOjEsInRlbmFudElkIjoxLCJncm91cHMiOlsiQURNSU4iXSwiaWF0IjoxNzg4MjAwMzY4LCJleHAiOjE3ODgzODAzNjgsImp0aSI6ImQ4NTcwZTg1LTNhNzMtNDJiNi1hODg2LTM1OTgyNmJiZGIxZiJ9.OWyQAQvTSrvKqJKN6sJWjaWOppUlt1H_2OHVWPfEgB7ka39HEPR4QOzdveROrNFvLkanIsMEueuw_iAzp1U0fHs1p_dVXSZTF07M6TC59zoO4sM3MBQhpQVaY5dKLmkAiLR2liIUaNBU9EhBWduru5xWYnqmIqWTdtCO8Lt8IjbuLdaBwsYtTuCebPN1X03FsBtTBOxoS3SyXTQ-Qw0IhPFZ5MChjIwqZlMzqcEkxJv2OlBxtklzLKTzA118UVUHswQc-80aPwGf60YX4zYMTlQojXXtabqbci8mwJ_uTLR-c0c6lu_P-AhjGe6QrHlh8UZwyCPGecColfmxgDD7OA

###
PUT http://localhost:8080/saas-admin/assign/7
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6Im1heC5tdXN0ZXJtYW5uQGZpcm1hLmF0IiwiaWQiOjEsInRlbmFudElkIjoxLCJncm91cHMiOlsiQURNSU4iXSwiaWF0IjoxNzg4MjAwMzY4LCJleHAiOjE3ODgzODAzNjgsImp0aSI6ImQ4NTcwZTg1LTNhNzMtNDJiNi1hODg2LTM1OTgyNmJiZGIxZiJ9.OWyQAQvTSrvKqJKN6sJWjaWOppUlt1H_2OHVWPfEgB7ka39HEPR4QOzdveROrNFvLkanIsMEueuw_iAzp1U0fHs1p_dVXSZTF07M6TC59zoO4sM3MBQhpQVaY5dKLmkAiLR2liIUaNBU9EhBWduru5xWYnqmIqWTdtCO8Lt8IjbuLdaBwsYtTuCebPN1X03FsBtTBOxoS3SyXTQ-Qw0IhPFZ5MChjIwqZlMzqcEkxJv2OlBxtklzLKTzA118UVUHswQc-80aPwGf60YX4zYMTlQojXXtabqbci8mwJ_uTLR-c0c6lu_P-AhjGe6QrHlh8UZwyCPGecColfmxgDD7OA


###
PUT http://localhost:8080/saas-admin/restaurant/7
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6Im1heC5tdXN0ZXJtYW5uQGZpcm1hLmF0IiwiaWQiOjEsInRlbmFudElkIjoxLCJncm91cHMiOlsiQURNSU4iXSwiaWF0IjoxNzg4MjAwMzY4LCJleHAiOjE3ODgzODAzNjgsImp0aSI6ImQ4NTcwZTg1LTNhNzMtNDJiNi1hODg2LTM1OTgyNmJiZGIxZiJ9.OWyQAQvTSrvKqJKN6sJWjaWOppUlt1H_2OHVWPfEgB7ka39HEPR4QOzdveROrNFvLkanIsMEueuw_iAzp1U0fHs1p_dVXSZTF07M6TC59zoO4sM3MBQhpQVaY5dKLmkAiLR2liIUaNBU9EhBWduru5xWYnqmIqWTdtCO8Lt8IjbuLdaBwsYtTuCebPN1X03FsBtTBOxoS3SyXTQ-Qw0IhPFZ5MChjIwqZlMzqcEkxJv2OlBxtklzLKTzA118UVUHswQc-80aPwGf60YX4zYMTlQojXXtabqbci8mwJ_uTLR-c0c6lu_P-AhjGe6QrHlh8UZwyCPGecColfmxgDD7OA


###
PUT http://localhost:8080/saas-admin/restaurant/2/user/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6Im1heC5tdXN0ZXJtYW5uQGZpcm1hLmF0IiwiaWQiOjEsInRlbmFudElkIjoxLCJncm91cHMiOlsiQURNSU4iXSwiaWF0IjoxNzg4MjAwMzY4LCJleHAiOjE3ODgzODAzNjgsImp0aSI6ImQ4NTcwZTg1LTNhNzMtNDJiNi1hODg2LTM1OTgyNmJiZGIxZiJ9.OWyQAQvTSrvKqJKN6sJWjaWOppUlt1H_2OHVWPfEgB7ka39HEPR4QOzdveROrNFvLkanIsMEueuw_iAzp1U0fHs1p_dVXSZTF07M6TC59zoO4sM3MBQhpQVaY5dKLmkAiLR2liIUaNBU9EhBWduru5xWYnqmIqWTdtCO8Lt8IjbuLdaBwsYtTuCebPN1X03FsBtTBOxoS3SyXTQ-Qw0IhPFZ5MChjIwqZlMzqcEkxJv2OlBxtklzLKTzA118UVUHswQc-80aPwGf60YX4zYMTlQojXXtabqbci8mwJ_uTLR-c0c6lu_P-AhjGe6QrHlh8UZwyCPGecColfmxgDD7OA

###
POST http://localhost:8080/saas-admin/costorder
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6Im1heC5tdXN0ZXJtYW5uQGZpcm1hLmF0IiwiaWQiOjEsInRlbmFudElkIjoxLCJncm91cHMiOlsiQURNSU4iXSwiaWF0IjoxNzg4MjAwMzY4LCJleHAiOjE3ODgzODAzNjgsImp0aSI6ImQ4NTcwZTg1LTNhNzMtNDJiNi1hODg2LTM1OTgyNmJiZGIxZiJ9.OWyQAQvTSrvKqJKN6sJWjaWOppUlt1H_2OHVWPfEgB7ka39HEPR4QOzdveROrNFvLkanIsMEueuw_iAzp1U0fHs1p_dVXSZTF07M6TC59zoO4sM3MBQhpQVaY5dKLmkAiLR2liIUaNBU9EhBWduru5xWYnqmIqWTdtCO8Lt8IjbuLdaBwsYtTuCebPN1X03FsBtTBOxoS3SyXTQ-Qw0IhPFZ5MChjIwqZlMzqcEkxJv2OlBxtklzLKTzA118UVUHswQc-80aPwGf60YX4zYMTlQojXXtabqbci8mwJ_uTLR-c0c6lu_P-AhjGe6QrHlh8UZwyCPGecColfmxgDD7OA
Content-Type: text/plain

140sdf0 - Marketing


###
GET http://localhost:8080/saas-admin/unassigned-employees

###
PUT http://localhost:8080/saas-admin/assign/1/9
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6Im1heC5tdXN0ZXJtYW5uQGZpcm1hLmF0IiwiaWQiOjEsInRlbmFudElkIjoxLCJncm91cHMiOlsiU0FBU19BRE1JTiJdLCJpYXQiOjE3OTA1MzkwODMsImV4cCI6MTc5MDcxOTA4MywianRpIjoiNjNjYmJmMzUtZWM5MS00OGEyLWJkMjUtNmU4YjM4YmE3N2E0In0.r9pVx_rAfxo1Uc6qzRcZTyidUz2hTvDuJgkgRNHxl_pbnIPJcPde35eFEL41ZsICLRqdPt4JCaf8wguzGWs6iT8c2pkdG6FBLjxjax64JOiaiA-gouOJwuDC35jP1mLxB5EGISxjEjcj9-XYCaeS_ZeSQ8xDGBgUKhd2SMPc401rsLVkEyotfeyu4opo_jL4u9HdxAs87aaVak_QQvVi-cexklZ8Vt4fN2GGMAbFu1Fq13iy4NZWQpuMMj4_bip4R7JqYbnqFUo5aolK41luwgzI8pn0hIJvA9GMe3fRytL-cF3_5Z2_bTEXnc7avV08TDNw_Q2tw5vjcmA5hikdhQ",



###
PUT http://localhost:8080/saas-admin/tenant/1
Content-Type: application/json

{
  "organisationName": "Test GmbH",
  "contactPerson": "Max Mustermann",
  "email": "max.mustermann@test.at",
  "country": "Austria",
  "primaryColor": "#005F99",
  "accentColor": "#E63946",
  "companySize": "50-249"
}


### GET - Alle Module + Aktivierungsstatus eines Tenants
GET http://localhost:8080/saas-admin/tenant/98981/modules
Accept: application/json


### PUT - Module für Tenant speichern
PUT http://localhost:8080/saas-admin/tenant/1/modules
Content-Type: application/json

{
  "moduleIds": [1, 2, 3, 4, 5, 6]
}




### GET - Regeln eines Tenants
GET http://localhost:8080/saas-admin/tenant/3/rules
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6Im1heC5tdXN0ZXJtYW5uQGZpcm1hLmF0IiwiaWQiOjEsInRlbmFudElkIjoxLCJncm91cHMiOlsiU0FBU19BRE1JTiJdLCJpYXQiOjE3OTA1MzkwODMsImV4cCI6MTc5MDcxOTA4MywianRpIjoiNjNjYmJmMzUtZWM5MS00OGEyLWJkMjUtNmU4YjM4YmE3N2E0In0.r9pVx_rAfxo1Uc6qzRcZTyidUz2hTvDuJgkgRNHxl_pbnIPJcPde35eFEL41ZsICLRqdPt4JCaf8wguzGWs6iT8c2pkdG6FBLjxjax64JOiaiA-gouOJwuDC35jP1mLxB5EGISxjEjcj9-XYCaeS_ZeSQ8xDGBgUKhd2SMPc401rsLVkEyotfeyu4opo_jL4u9HdxAs87aaVak_QQvVi-cexklZ8Vt4fN2GGMAbFu1Fq13iy4NZWQpuMMj4_bip4R7JqYbnqFUo5aolK41luwgzI8pn0hIJvA9GMe3fRytL-cF3_5Z2_bTEXnc7avV08TDNw_Q2tw5vjcmA5hikdhQ
Accept: application/json


### PUT - Regeln speichern
PUT http://localhost:8080/saas-admin/tenant/3/rules
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6Im1heC5tdXN0ZXJtYW5uQGZpcm1hLmF0IiwiaWQiOjEsInRlbmFudElkIjoxLCJncm91cHMiOlsiU0FBU19BRE1JTiJdLCJpYXQiOjE3OTA1MzkwODMsImV4cCI6MTc5MDcxOTA4MywianRpIjoiNjNjYmJmMzUtZWM5MS00OGEyLWJkMjUtNmU4YjM4YmE3N2E0In0.r9pVx_rAfxo1Uc6qzRcZTyidUz2hTvDuJgkgRNHxl_pbnIPJcPde35eFEL41ZsICLRqdPt4JCaf8wguzGWs6iT8c2pkdG6FBLjxjax64JOiaiA-gouOJwuDC35jP1mLxB5EGISxjEjcj9-XYCaeS_ZeSQ8xDGBgUKhd2SMPc401rsLVkEyotfeyu4opo_jL4u9HdxAs87aaVak_QQvVi-cexklZ8Vt4fN2GGMAbFu1Fq13iy4NZWQpuMMj4_bip4R7JqYbnqFUo5aolK41luwgzI8pn0hIJvA9GMe3fRytL-cF3_5Z2_bTEXnc7avV08TDNw_Q2tw5vjcmA5hikdhQ
Content-Type: application/json

{
  "usageDays": [
    "MONDAY",
    "TUESDAY",
    "WEDNESDAY",
    "THURSDAY",
    "FRIDAY"
  ],
  "restaurantRequired": true,
  "correctionHints": true
}





### GET - Branding eines Tenants
GET http://localhost:8080/saas-admin/tenant/1/branding
Accept: application/json


### PUT - Branding-Entwurf speichern
PUT http://localhost:8080/saas-admin/tenant/1/branding
Content-Type: application/json

{
  "appName": "ValidEat Test",
  "shortName": "ValidEat",
  "primaryColor": "#005Fdfgsdfdfg99",
  "accentColor": "#E63946",
  "logo": null
}


### GET - Branding erneut abrufen
GET http://localhost:8080/saas-admin/tenant/1/branding
Accept: application/json


### POST - Branding veröffentlichen
POST http://localhost:8080/saas-admin/tenant/1/branding/publish
Accept: application/json


### GET - Nach Veröffentlichung nochmals prüfen
GET http://localhost:8080/saas-admin/tenant/1/branding
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJWYWxpZEVhdCIsInN1YiI6Im1heC5tdXN0ZXJtYW5uQGZpcm1hLmF0IiwiaWQiOjEsInRlbmFudElkIjoxLCJncm91cHMiOlsiU0FBU19BRE1JTiJdLCJpYXQiOjE3OTA1MzkwODMsImV4cCI6MTc5MDcxOTA4MywianRpIjoiNjNjYmJmMzUtZWM5MS00OGEyLWJkMjUtNmU4YjM4YmE3N2E0In0.r9pVx_rAfxo1Uc6qzRcZTyidUz2hTvDuJgkgRNHxl_pbnIPJcPde35eFEL41ZsICLRqdPt4JCaf8wguzGWs6iT8c2pkdG6FBLjxjax64JOiaiA-gouOJwuDC35jP1mLxB5EGISxjEjcj9-XYCaeS_ZeSQ8xDGBgUKhd2SMPc401rsLVkEyotfeyu4opo_jL4u9HdxAs87aaVak_QQvVi-cexklZ8Vt4fN2GGMAbFu1Fq13iy4NZWQpuMMj4_bip4R7JqYbnqFUo5aolK41luwgzI8pn0hIJvA9GMe3fRytL-cF3_5Z2_bTEXnc7avV08TDNw_Q2tw5vjcmA5hikdhQ
Accept: application/json