apiVersion: apps/v1
kind: Deployment
metadata:
  name: valideat-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valideat-frontend
  template:
    metadata:
      labels:
        app: valideat-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: valideat-frontend
          image: ghcr.io/richterjulian/valideat-web:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"