# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/valideat
quarkus.datasource.username=valideat
quarkus.datasource.password=valideat

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

# show executed SQL-statements
quarkus.hibernate-orm.log.sql=true


mp.jwt.verify.issuer=ValidEat

smallrye.jwt.sign.key.location=privateKey-pkcs8.pem
mp.jwt.verify.publickey.location=publicKey.pem

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*

# blockchain
blockchain.rpc=http://127.0.0.1:8545
blockchain.contract=0x5FbDB2315678afecb367f032d93F642f64180aa3
blockchain.private-key=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80